Card.create!(
  [
    { card_type: 0, text: "But online I read that _____." },
    { card_type: 0, text: "11 reasons to _____. Nr 5 will surprise you." },
    { card_type: 0, text: "9gags most upvoted post is _____." },
    { card_type: 0, text: "After successfully selling my company I now _____." },
    { card_type: 0, text: "After ten years working as a developer, I am addicted to _____." },
    { card_type: 0, text: "As a hobby project I _____." },
    { card_type: 0, text: "Customer always complain about _____ in our software." },
    { card_type: 0, text: "Deploying my application in _____." },
    { card_type: 0, text: "Excel should be used for _____ more often." },
    { card_type: 0, text: "Fixing bugs by _____." },
    { card_type: 0, text: "For relaxing I do _____." },
    { card_type: 0, text: "High quality software is made with _____" },
    { card_type: 0, text: "I am using _____ for my monolith." },
    { card_type: 0, text: "I asked my boss for a raise due to _____." },
    { card_type: 0, text: "I declined the pull request because of _____." },
    { card_type: 0, text: "I don't get laid because of _____." },
    { card_type: 0, text: "I don't get paid because of _____." },
    { card_type: 0, text: "I don't need backups, I have _____." },
    { card_type: 0, text: "I filed a bug on _____." },
    { card_type: 0, text: "I integrated _____ into my DevSecOps pipeline." },
    { card_type: 0, text: "I like to get drunk and _____." },
    { card_type: 0, text: "I like to turn up to investor meetings _____." },
    { card_type: 0, text: "I spent my last salary on _____." },
    { card_type: 0, text: "I successfully tested _____." },
    { card_type: 0, text: "I switched to Linux because of _____." },
    { card_type: 0, text: "I would sell my shares of the company for _____." },
    { card_type: 0, text: "Last deployment failed because of _____." },
    { card_type: 0, text: "Last time I went outside, I experienced _____." },
    { card_type: 0, text: "Last year North Korea spent 10 million on _____." },
    { card_type: 0, text: "My Cloud Drive won't sync because of _____." },
    { card_type: 0, text: "My alternative to the gym is _____." },
    { card_type: 0, text: "My co-worker files a complaint because of _____." },
    { card_type: 0, text: "My job feels like _____." },
    { card_type: 0, text: "My morning toilet session can be explained as _____." },
    { card_type: 0, text: "My security is so good, it _____." },
    { card_type: 0, text: "On my GitHub profile you will find _____." },
    { card_type: 0, text: "On our Offsite we did _____." },
    { card_type: 0, text: "Our USP is _____." },
    { card_type: 0, text: "Our systems for _____ runs only on raspberry pies." },
    { card_type: 0, text: "Software development is like _____." },
    { card_type: 0, text: "The 11-star user experience is _____." },
    { card_type: 0, text: "The booth is themed _____." },
    { card_type: 0, text: "The customer requests _____." },
    { card_type: 0, text: "The difference between RSA and DSA is _____." },
    { card_type: 0, text: "The new marketing campaign for April 1st will be _____." },
    { card_type: 0, text: "The next blog article will be about _____." },
    { card_type: 0, text: "The next superior cloud service will use _____." },
    { card_type: 0, text: "There still is a bug in _____." },
    { card_type: 0, text: "This year's marketing motto is _____." },
    { card_type: 0, text: "We use _____ for quality control." },
    { card_type: 0, text: "When the marketing intern asks: Can you please change _____ on the website" },
    { card_type: 0, text: "When the sales guys are laughing in their office they are _____." },
    { card_type: 0, text: "Yesterday Bill Gates asked me _____" },
    { card_type: 0, text: "_____ as a Service" },
    { card_type: 0, text: "_____ makes the CEO happy." },
    { card_type: 0, text: "_____. How did this ever work?" },
    { card_type: 0, text: "_____. Oh, this was earlier than expected." },
    { card_type: 1, text: "Did you try turning it off and on again?" },
    { card_type: 1, text: "I destroyed the internet" },
    { card_type: 1, text: "I tested it" },
    { card_type: 1, text: "Your opinion" },
    { card_type: 1, text: "45 minutes daily standup" },
    { card_type: 1, text: "A fridge filled with club mate" },
    { card_type: 1, text: "A missing semicolon" },
    { card_type: 1, text: "A short nap" },
    { card_type: 1, text: "A three day build pipeline" },
    { card_type: 1, text: "A/B testing" },
    { card_type: 1, text: "AI Hackathon" },
    { card_type: 1, text: "AI based sex toys" },
    { card_type: 1, text: "An oversized office chair" },
    { card_type: 1, text: "Backdoor Traffic" },
    { card_type: 1, text: "Beer Pong as a team event" },
    { card_type: 1, text: "Beer in the office" },
    { card_type: 1, text: "Being oddly specific" },
    { card_type: 1, text: "Big Data driven business model" },
    { card_type: 1, text: "Bill Gates" },
    { card_type: 1, text: "Black holes" },
    { card_type: 1, text: "Blinking ads" },
    { card_type: 1, text: "Browsing StackOverflow for hours without actually looking for a solution" },
    { card_type: 1, text: "Bruce Schneier" },
    { card_type: 1, text: "Burger Tuesday" },
    { card_type: 1, text: "CORS Headers" },
    { card_type: 1, text: "Cat videos" },
    { card_type: 1, text: "Church of the flying spaghetti monster" },
    { card_type: 1, text: "Code monkeys" },
    { card_type: 1, text: "Cold leftover pizza from last week" },
    { card_type: 1, text: "Comic Con" },
    { card_type: 1, text: "Commenting it out" },
    { card_type: 1, text: "Compilation error" },
    { card_type: 1, text: "Copy & Pasting from StackOverflow" },
    { card_type: 1, text: "Creating a buffer overflow" },
    { card_type: 1, text: "Cuddling with ewoks" },
    { card_type: 1, text: "Customer touchpoints" },
    { card_type: 1, text: "Darknet Marketplace" },
    { card_type: 1, text: "Darude Sandstorm" },
    { card_type: 1, text: "Day Drinking" },
    { card_type: 1, text: "Deleting one cell in Excel wrathing your whole data model" },
    { card_type: 1, text: "Deodorant instead of showers" },
    { card_type: 1, text: "DevOps Engineers" },
    { card_type: 1, text: "DevSecOps" },
    { card_type: 1, text: "Displaying success messages in red color to scare the hell out of others" },
    { card_type: 1, text: "Don't lick it" },
    { card_type: 1, text: "Donald Trump" },
    { card_type: 1, text: "Dry humping" },
    { card_type: 1, text: "Ejecting USB drives unsafely" },
    { card_type: 1, text: "Elon Musk" },
    { card_type: 1, text: "End to end encryption with a non-revocable static key" },
    { card_type: 1, text: "Explosive diarrhea" },
    { card_type: 1, text: "Fair hostesses" },
    { card_type: 1, text: "Fast food, five times a week" },
    { card_type: 1, text: "Fixing bugs during the penetration test" },
    { card_type: 1, text: "Forget to lock my computer" },
    { card_type: 1, text: "Going to prom naked" },
    { card_type: 1, text: "Hacker bootcamp" },
    { card_type: 1, text: "Hacking Vibrators" },
    { card_type: 1, text: "Having the last word" },
    { card_type: 1, text: "Hoodies and Ski masks" },
    { card_type: 1, text: "It is always a good idea to change a running system" },
    { card_type: 1, text: "It worked on staging" },
    { card_type: 1, text: "It's a feature" },
    { card_type: 1, text: "Just a minor refactoring" },
    { card_type: 1, text: "KISS" },
    { card_type: 1, text: "Layer 8 problem" },
    { card_type: 1, text: "Leaving the backdoor open" },
    { card_type: 1, text: "Legacy Code" },
    { card_type: 1, text: "Living in my mother's basement" },
    { card_type: 1, text: "Looking like I care" },
    { card_type: 1, text: "Lucky13" },
    { card_type: 1, text: "Magic Numbers" },
    { card_type: 1, text: "Making small changes in production" },
    { card_type: 1, text: "Male underboob sweat" },
    { card_type: 1, text: "Marc Zuckerberg" },
    { card_type: 1, text: "Microservice Architecture" },
    { card_type: 1, text: "Minecraft" },
    { card_type: 1, text: "My lovelife" },
    { card_type: 1, text: "NAT allergy" },
    { card_type: 1, text: "Not wearing pants during video chats" },
    { card_type: 1, text: "Null pointer exception" },
    { card_type: 1, text: "Nyan Cat" },
    { card_type: 1, text: "Old people smell" },
    { card_type: 1, text: "Opening an alpaca farm" },
    { card_type: 1, text: "Outsourcing to India" },
    { card_type: 1, text: "Overspecified requirements" },
    { card_type: 1, text: "PHP" },
    { card_type: 1, text: "Panda porn" },
    { card_type: 1, text: "Penetration without testing" },
    { card_type: 1, text: "Playing Mario cart.... in single player mode" },
    { card_type: 1, text: "Please beautify" },
    { card_type: 1, text: "Plugging in a USB drive correctly the first time" },
    { card_type: 1, text: "Plumber's smile" },
    { card_type: 1, text: "Popping the stack" },
    { card_type: 1, text: "Python" },
    { card_type: 1, text: "Quadrocopter with infrared camera" },
    { card_type: 1, text: "Quick fix" },
    { card_type: 1, text: "Quick search" },
    { card_type: 1, text: "Quoting the Big Bang Theory" },
    { card_type: 1, text: "Reading the Youporn blog entries on technology for research purposes" },
    { card_type: 1, text: "Rebasing" },
    { card_type: 1, text: "Releasing features early" },
    { card_type: 1, text: "Releasing too early" },
    { card_type: 1, text: "Remote access" },
    { card_type: 1, text: "Reviewing pull requests" },
    { card_type: 1, text: "Rooftop barbecue party" },
    { card_type: 1, text: "Running a conference completely with volunteers" },
    { card_type: 1, text: "STDs" },
    { card_type: 1, text: "Scope Creep" },
    { card_type: 1, text: "Script Kiddy" },
    { card_type: 1, text: "Server farms" },
    { card_type: 1, text: "Shared Memory" },
    { card_type: 1, text: "Smiling a little bit too much" },
    { card_type: 1, text: "Software rollback" },
    { card_type: 1, text: "Something written in Fortran" },
    { card_type: 1, text: "Steve Jobs" },
    { card_type: 1, text: "Stormtroopers for quality control" },
    { card_type: 1, text: "Sun rays" },
    { card_type: 1, text: "Swinging my light saber" },
    { card_type: 1, text: "Swiping left and right" },
    { card_type: 1, text: "Technical Difficulties" },
    { card_type: 1, text: "Ten layered if statements" },
    { card_type: 1, text: "Terraforming" },
    { card_type: 1, text: "Testing early" },
    { card_type: 1, text: "Testing in production" },
    { card_type: 1, text: "That can't be too complicated" },
    { card_type: 1, text: "The 16th internship in the 12th company" },
    { card_type: 1, text: "The Linux Kernel" },
    { card_type: 1, text: "The dark side of the force" },
    { card_type: 1, text: "The difference between machine learning and AI" },
    { card_type: 1, text: "Tinder newsletter" },
    { card_type: 1, text: "Tiny student dorms" },
    { card_type: 1, text: "Too many hot girls" },
    { card_type: 1, text: "Touch control" },
    { card_type: 1, text: "Touching my joystick" },
    { card_type: 1, text: "Touching myself" },
    { card_type: 1, text: "Tripping the wire" },
    { card_type: 1, text: "Unexpected side effects" },
    { card_type: 1, text: "Unicorns" },
    { card_type: 1, text: "Useless meeting" },
    { card_type: 1, text: "User space function calls" },
    { card_type: 1, text: "Using Blockchain instead of a database" },
    { card_type: 1, text: "Using HTML as a programming language" },
    { card_type: 1, text: "Using Tabs instead of Spaces" },
    { card_type: 1, text: "Using XML instead of JSON" },
    { card_type: 1, text: "Using a light theme for the terminal" },
    { card_type: 1, text: "Using blockchain in every pitch" },
    { card_type: 1, text: "Using kubernetes for my static website with 100 visitors per month" },
    { card_type: 1, text: "Using more than 10 programming languages because I can" },
    { card_type: 1, text: "Using open source software just because it's free" },
    { card_type: 1, text: "Vendor lock Stockholm syndrome" },
    { card_type: 1, text: "Watching Porn over the company vpn" },
    { card_type: 1, text: "Whistling the Tetris theme song" },
    { card_type: 1, text: "Winking at old people" },
    { card_type: 1, text: "Winning because of psychological warfare" },
    { card_type: 1, text: "Writing code without my supervisor telling me what to do" },
    { card_type: 1, text: "LaTeX" },
    { card_type: 1, text: "git --force push" },
    { card_type: 1, text: "iOS developers" },
    { card_type: 1, text: "in $O(1)$" },
    { card_type: 1, text: "rm -rf /" },
    { card_type: 1, text: "sudo" },
  ]
)
